name: build
on: push
jobs:

  proto-compile:
    name: Compile proto
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: build
      run: build.sh
